export const knowledgeBase = {
  cabins: "🏡 Our cabins blend rustic charm with luxury — each offers a private balcony overlooking the Himalayas.",
  booking: "📅 You can book directly through our website or call our front desk for assistance with reservations.",
  restaurant: "🍽️ The Wilderness restaurant serves gourmet mountain cuisine using fresh, local ingredients.",
  spa: "💆 Our spa offers Himalayan salt therapies, aromatherapy massages, and a tranquil relaxation zone.",
  checkin: "🕒 Check-in begins at 2 PM and check-out is by 11 AM. Early check-in is available upon request.",
  checkout: "🕚 Standard check-out is 11 AM. Late check-out may be available depending on occupancy.",
  wifi: "📶 Complimentary high-speed Wi-Fi is available in all cabins and common areas.",
  activities: "🎒 Guests can enjoy trekking, stargazing, bonfires, and local cultural experiences.",
  weather: "🌤️ The weather in the Himalayas varies — mornings are cool and evenings can get chilly. Warm clothing recommended!",
  location: "📍 The Wilderness is located in the serene Himalayan foothills, about 2 hours from the nearest airport.",
  transport: "🚗 We provide pickup and drop-off services upon request. Local taxis and jeeps are also available.",
  contact: "☎️ You can reach our front desk anytime at +91-9876543210 or email us at stay@thewilderness.com.",
  pool: "🏊 Our heated infinity pool overlooks the pine forests — perfect for relaxation any time of year.",
  payment: "💳 We accept all major credit cards and UPI payments.",
  refund: "🔁 Cancellations made 48 hours before arrival are fully refundable.",
  gym: "🏋️ Our fitness center offers cardio and strength equipment with a stunning mountain view.",
  kids: "👶 Families are welcome! We have kids’ play zones, babysitting on request, and family cabins.",
  parking: "🚘 Complimentary valet parking is available for all guests.",
  breakfast: "🥐 Complimentary breakfast is served daily from 7 AM to 10 AM at our main restaurant.",
  dinner: "🍛 Dinner is served from 7 PM to 10 PM — advance reservations are recommended during weekends.",
  pets: "🐾 The Wilderness is pet-friendly! Please inform us in advance if bringing a pet.",
  bar: "🍸 Our mountain-view bar offers handcrafted cocktails and local brews — open daily from 5 PM to 11 PM.",
  honeymoon: "💞 Planning a honeymoon? Ask about our romantic packages with private dinners and spa treatments.",
  cancellation: "❌ Cancellations made within 48 hours of check-in are subject to one night’s charge.",
  roomservice: "🛎️ Room service is available from 7 AM to 11 PM. Dial ‘0’ from your cabin phone to order.",
  fireplace: "🔥 Each cabin includes a cozy indoor fireplace stocked with complimentary firewood.",
  sightseeing: "🏔️ Nearby attractions include Pine Valley Viewpoint, Serenity Lake, and the Old Monastery Trail.",
  reservation: "📆 To modify or cancel your reservation, contact us at stay@thewilderness.com.",
  safety: "🧯 Our property is equipped with 24-hour security and emergency support staff.",
  staff: "😊 Our friendly staff is available 24/7 to assist with anything you need during your stay.",
  laundry: "👕 Laundry and dry-cleaning services are available on request — usually returned within 24 hours.",
  giftshop: "🎁 The Wilderness Gift Shop offers handmade souvenirs, organic teas, and local crafts.",
  firepit: "🔥 Communal firepits are lit every evening at 7 PM — a great way to meet fellow travelers.",
  couples: "💑 Couples love our private hot tubs and candlelit dining options with panoramic mountain views.",
  family: "👨‍👩‍👧 Family-friendly cabins with extra beds and kids’ play areas are available.",
  hiking: "🥾 Guided hikes are available daily at 8 AM and 4 PM. Sign up at the front desk.",
  yoga: "🧘 Morning yoga sessions are held at sunrise on our open-air deck overlooking the peaks.",
  feedback: "📝 We value your feedback! Please share your experience at reception or via our website form.",
  emergency: "🚨 In case of any emergency, dial ‘9’ from your cabin or contact our 24-hour helpdesk.",
  temperature: "🌡️ Average temperatures range from 10°C to 25°C — cooler at night, especially in winter.",
  events: "🎉 We host small weddings, retreats, and corporate events. Contact us for custom arrangements.",
  adventure: "⛰️ For thrill-seekers, we offer mountain biking, river crossing, and paragliding experiences nearby.",
  sustainability: "🌱 The Wilderness is eco-friendly — we use solar power, rainwater harvesting, and no single-use plastics.",
  photography: "📸 Our scenic trails and sunrise decks are perfect for photography enthusiasts!",
  meditation: "🕯️ Daily guided meditation sessions are held in our tranquility hall at 6 AM and 7 PM.",
  weddings: "💍 Dreaming of a mountain wedding? We offer full destination wedding services and decor.",
  festivals: "🎊 We celebrate local festivals like Diwali and Holi with bonfires, music, and traditional feasts.",
  transportation: "🚐 We provide airport shuttle services and can arrange local sightseeing transport upon request.",
  security: "🔒 The resort is monitored by CCTV and staffed with 24/7 security personnel for your safety.",
  naturewalk: "🌿 Join our nature walk every morning to explore the flora and fauna of the Himalayan region.",
  bonfire: "🔥 Evening bonfires with live music are held daily near the lounge area — don’t miss it!",
  tea: "🍵 Try our organic mountain tea blends served at the café all day.",
  coffee: "☕ Freshly brewed local coffee is available in all cabins and at the main restaurant.",
  lounge: "🛋️ The mountain-view lounge is perfect for reading, relaxing, or enjoying a quiet evening indoors.",
  concierge: "💼 Our concierge team can help you plan excursions, book taxis, or arrange special surprises.",
  souvenirs: "🎨 Take home a piece of the Himalayas — visit our souvenir shop near the main lobby.",
  adventurepark: "🎢 Kids and adults alike will enjoy our adventure park with zip lines and rope courses.",
  cultural: "🎭 Experience local Himalayan culture through evening performances and craft fairs every weekend.",
  guide: "🧭 Our certified local guides ensure safe and informative treks and nature walks.",
  drinks: "🍹 Enjoy refreshing mocktails and cocktails crafted from local herbs and fruits at our Sunset Bar.",
  housekeeping: "🧺 Daily housekeeping ensures your cabin remains spotless throughout your stay.",
  garden: "🌸 Wander through our herbal garden, where we grow fresh ingredients for the restaurant.",
  mountainview: "🏔️ Most cabins offer a panoramic view of the snow-capped Himalayas right from your balcony.",
  celebration: "🎂 Celebrating something special? We can arrange private dinners, cakes, and decorations.",
  packages: "🎁 Check out our seasonal packages for couples, families, and adventure seekers.",
  membership: "💎 Join our loyalty program for exclusive discounts and early access to offers."
};
